
spring:
  profiles:
    active: local
  application:
    name: rabbit-consumer
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    
server:
  port: 8081
  servlet:
    context-path: /rabbit-consumer
  
logging:
  level:
    org.springframework: ERROR
    com.example.demo: DEBUG

tutorial:
  client:
    duration: 10000