spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Univangr/microservices-complete-config.git
          clone-on-start: true
    
server:
  port: 8888
  
logging:
  level:
    org.springframework: ERROR
    com.example.demo: DEBUG